"use client";
import { ArrowUpRight, CheckCircle2, LoaderCircle } from "lucide-react";
import { FormEvent, useState } from "react";
type State = "idle" | "loading" | "success" | "error";
export function ContactForm() {
  const [state, setState] = useState<State>("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("loading"); setMessage(""); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form)); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Something went wrong."); setState("success"); setMessage("Message received. I’ll get back to you soon."); form.reset(); } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "Unable to send your message."); } }
  return <form className="contact-form" onSubmit={submit}><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><label><span>01 / Your name</span><input name="name" minLength={2} maxLength={80} required placeholder="What should I call you?" /></label><label><span>02 / Email address</span><input name="email" type="email" maxLength={160} required placeholder="you@company.com" /></label><label><span>03 / Reason for contact</span><select name="project_type" required defaultValue=""><option value="" disabled>Choose one</option><option>Job opportunity</option><option>Internship</option><option>Full stack project</option><option>Collaboration</option><option>Something else</option></select></label><label><span>04 / Your message</span><textarea name="message" minLength={10} maxLength={2000} required rows={4} placeholder="Tell me about the opportunity or project..." /></label><button type="submit" disabled={state === "loading"}>{state === "loading" ? <LoaderCircle className="spin" /> : state === "success" ? <CheckCircle2 /> : <ArrowUpRight />}{state === "loading" ? "Sending" : "Send message"}</button>{message && <p className={`form-message ${state}`}>{message}</p>}</form>;
}
